# IS 362 – Week 5 Assignment

## Your task in this week’s assignment is to answer three questions:
#1 What is the northernmost airport in the United States?
#2 What is the easternmost airport in the United States?
#3 On February 12th, 2013, which New York area airport had the windiest weather?
### Data taken from: https://github.com/hadley/nycflights13/tree/master/data-raw

In [20]:
import pandas as pd

airport_data = 'airports.csv'
airport_df = pd.read_csv(airport_data)

weather_data = 'weather.csv'
weather_df = pd.read_csv(weather_data)

airport_df

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York
...,...,...,...,...,...,...,...,...
1453,ZUN,Black Rock,35.083228,-108.791778,6454,-7,A,America/Denver
1454,ZVE,New Haven Rail Station,41.298669,-72.925992,7,-5,A,America/New_York
1455,ZWI,Wilmington Amtrak Station,39.736667,-75.551667,0,-5,A,America/New_York
1456,ZWU,Washington Union Station,38.897460,-77.006430,76,-5,A,America/New_York
1457,ZYP,Penn Station,40.750500,-73.993500,35,-5,A,America/New_York

### Question 1:
#### What is the northernmost airport in the United States?

In [21]:
airport_df.nlargest(10, 'lat')

,faa,name,lat,lon,alt,tz,dst,tzone
417,EEN,Dillant Hopkins Airport,72.270833,42.898333,149,-5,A,NaN
230,BRW,Wiley Post Will Rogers Mem,71.285446,-156.766003,44,-9,A,America/Anchorage
110,AIN,Wainwright Airport,70.638056,-159.994722,41,-9,A,America/Anchorage
708,K03,Wainwright As,70.613378,-159.860350,35,-9,A,America/Anchorage
152,ATK,Atqasuk Edward Burnell Sr Memorial Airport,70.467300,-157.436000,96,-9,A,America/Anchorage
1363,UUK,Ugnu-Kuparuk Airport,70.330833,-149.597500,67,-9,A,America/Anchorage
982,NUI,Nuiqsut Airport,70.210000,-151.005556,38,-9,A,America/Anchorage
1197,SCC,Deadhorse,70.194750,-148.465167,64,-9,A,America/Anchorage
232,BTI,Barter Island Lrrs,70.133989,-143.581867,2,-9,A,America/Anchorage
1084,PIZ,Point Lay Lrrs,69.732875,-163.005342,25,-9,A,America/Anchorage

### Answer 1:
#### Based on the data provided, Dillant Hopkins Airpot (EEN) has the highest Latitude coordinate but this information is incorrect. The values for Latitude and Longitude have been reversed - this airport is actually in New Hampshire.
#### Reference: https://skyvector.com/airport/EEN/Dillant-Hopkins-Airport
#### "Wiley Post–Will Rogers Memorial Airport (BRW) is a public airport located in Utqiaġvik (formerly Barrow), the largest city and borough seat of the North Slope Borough of the U.S. state of Alaska. The airport is owned by the state. Situated on the Chukchi Sea at a latitude of 71.29°N, the airport is the farthest north of any in US territory.:
#### Reference: https://en.wikipedia.org/wiki/Wiley_Post%E2%80%93Will_Rogers_Memorial_Airport

### Question 2:
#### What is the easternmost airport in the United States?

In [25]:
airport_df.nlargest(10, 'lon')

,faa,name,lat,lon,alt,tz,dst,tzone
1290,SYA,Eareckson As,52.712275,174.113620,98,-9,A,America/Anchorage
942,MYF,Montgomery Field,32.475900,117.759000,17,8,A,Asia/Chongqing
396,DVT,Deer Valley Municipal Airport,33.411700,112.457000,1478,8,A,Asia/Chongqing
417,EEN,Dillant Hopkins Airport,72.270833,42.898333,149,-5,A,NaN
444,EPM,Eastport Municipal Airport,44.910111,-67.012694,45,-5,A,America/New_York
624,HUL,Houlton Intl,46.123083,-67.792056,489,-5,A,America/New_York
259,CAR,Caribou Muni,46.871500,-68.017917,626,-5,A,America/New_York
1101,PQI,Northern Maine Rgnl At Presque Isle,46.688958,-68.044797,534,-5,A,America/New_York
1398,WFK,Northern Aroostook Regional Airport,47.285556,-68.312778,988,-5,A,America/New_York
192,BHB,Hancock County - Bar Harbor,44.449769,-68.361565,83,-5,A,America/New_York

### Answer 2:
#### According to this data, Eastport Municpal Airport in Eastport Maine is the eastern-most airport in the United States
#### Reference: https://www.eastport-me.gov/eastport-municipal-airport-kepm

### Question 3:
#### On February 12th, 2013, which New York area airport had the windiest weather?

In [19]:
weather_df.nlargest(10, 'wind_speed')

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
1009,EWR,2013,2,12,3,39.02,26.96,61.63,260.0,1048.36058,NaN,0.00,1008.3,10.0,2013-02-12T08:00:00Z
724,EWR,2013,1,31,6,57.20,53.60,87.74,270.0,42.57886,55.23744,0.03,NaN,10.0,2013-01-31T11:00:00Z
9425,JFK,2013,1,31,4,53.60,53.06,100.00,200.0,42.57886,52.93588,0.20,NaN,2.0,2013-01-31T09:00:00Z
722,EWR,2013,1,31,4,60.80,59.00,93.79,230.0,40.27730,58.68978,0.30,NaN,6.0,2013-01-31T09:00:00Z
18131,LGA,2013,1,31,4,59.00,55.40,93.69,230.0,40.27730,55.23744,0.41,NaN,8.0,2013-01-31T09:00:00Z
726,EWR,2013,1,31,8,46.04,30.02,53.33,270.0,39.12652,48.33276,0.00,992.3,10.0,2013-01-31T13:00:00Z
10249,JFK,2013,3,6,14,41.00,28.94,61.89,50.0,37.97574,46.03120,0.00,NaN,10.0,2013-03-06T19:00:00Z
9424,JFK,2013,1,31,3,53.06,51.98,100.00,180.0,36.82496,48.33276,0.07,NaN,1.0,2013-01-31T08:00:00Z
9428,JFK,2013,1,31,7,51.80,46.40,81.74,270.0,36.82496,58.68978,0.00,NaN,10.0,2013-01-31T12:00:00Z
16536,JFK,2013,11,24,10,28.04,-0.04,29.16,310.0,36.82496,47.18198,0.00,1021.5,10.0,2013-11-24T15:00:00Z

### Answer 3:
#### According to the data Newark Liberty Airport (EWR) had the windiest weather on Feb 12th, 2013